// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qinbteuulduxmyeavzgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpbmJ0ZXV1bGR1eG15ZWF2emdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzQxNTQsImV4cCI6MjA2Mzg1MDE1NH0.Fi1umdY0m-vlP9foC7P61vdk8ENfSwbKuDrlKuISh3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);